# -*- coding: utf-8 -*-
"""3_lab_networks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fSTeUwg8gXbvsKzzZGt8H63EbM6mUB8
"""

import networkx as nx

n = 50  # число вершин графа
p = 0.65  # вероятность появления случайного ребра
G = nx.erdos_renyi_graph(n, p)  # генерация графа

# расчет средней степени вершин
a = 0
for n in G.nodes():
    a = a + G.degree(n)

# Вывод результатов
print(f"Полученная средняя степень вершин: {float(a) / len(G.nodes())}")
print(f"Теоретическая средняя степень вершин: {(n-1)*p}")

